# Database
spring.datasource.url=jdbc:mysql://localhost:3306/autibridge
spring.datasource.username=root
spring.datasource.password=rajas
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret= abcauydv$@%!%N(*623t36g27vdvyafd7327231252mhdyggs7^&b328hdgd7gdvwtfevdwtvewd
jwt.expiration=86400000

# App
server.port=8080